#include <iostream>
#include <iomanip>
#include <algorithm>
#include <vector>
#include <string>
#include <time.h>

using std::cin;
using std::cout;
using std::setw;
using std::setprecision;
using std::endl;
using std::left;
using std::copy;
using std::copy_n;
using std::sort;
using std::fixed;
using std::numeric_limits;
using std::streamsize;
using std::vector;
using std::string;
using std::_Char_traits;
