#pragma once
#include <iostream>
#include <iomanip>
#include <algorithm>
#include <string>
#include <time.h>
#include <vector>
#include <fstream>
#include <istream>
#include <sstream>
#include <cstdlib>
#include <thread>
#include <chrono>
#include <atomic>
#include <random>
#include <algorithm>
#include <numeric>
#include <memory>
#include <utility>

using std::cin;
using std::cout;
using std::cerr;
using std::setw;
using std::setprecision;
using std::endl;
using std::left;
using std::copy;
using std::copy_n;
using std::sort;
using std::fixed;
using std::getline;
using std::flush;
using std::srand;
using std::stringstream;
using std::ios;
using std::istream;
using std::ifstream;
using std::ofstream;
using std::vector;
using std::streamsize;
using std::string;
using std::_Char_traits;
using std::numeric_limits;
using std::runtime_error;
using std::exception;
