#include <iostream>
#include <iomanip>
#include <algorithm>
#include <string>
#include <time.h>
#include <vector>
#include <fstream>
#include <istream>
#include <sstream>

using std::cin;
using std::cout;
using std::cerr;
using std::setw;
using std::setprecision;
using std::endl;
using std::left;
using std::copy;
using std::copy_n;
using std::sort;
using std::fixed;
using std::getline;
using std::stringstream;
using std::ios;
using std::istream;
using std::ifstream;
using std::vector;
using std::numeric_limits;
using std::streamsize;
using std::string;
using std::_Char_traits;
